### ISSUE TITLE
Для всех exception сделать @ExceptionHandler и всю обработку ошибок реализовать там, не бросаться эксепшнами на каждом уровне

### ISSUE THREAD

**Issue by sboriskin287** [kjluh/EgarTask#17]
https://github.com/kjluh/EgarTask/blob/2cb2f93f7519ee0f794bf699731b8457397b22af/src/main/java/egar/egartask/service/SalaryService.java#L121

**Comment by sboriskin287** [comment]
и где @ExceptionHandler???

**Comment by kjluh** [comment]
https://github.com/kjluh/EgarTask/blob/master/src/main/java/egar/egartask/controllers/ExceptionController.java
для всего приложения.
