### ISSUE TITLE
@transactional над классом не лучшая практика, лучше на конкретный метод(ы) повесить. И точно не надо использовать в репозиториях, лучше ев сервисах

### ISSUE THREAD

**Issue by sboriskin287** [kjluh/EgarTask#18]
https://github.com/kjluh/EgarTask/blob/2cb2f93f7519ee0f794bf699731b8457397b22af/src/main/java/egar/egartask/repository/DepartmentRepository.java#L14

**Comment by sboriskin287** [comment]
ставить @transactional везде где захочется, тоже так себе затея. Разобраться в каких случаях используются транзакции, и убрать из не нужных мест. Подсказка, по умолчанию методы из JpaRepository уже открывают транзакцию, даже если нет явного указания в коде (@Transactional, TransactionTemplate, em.getTransaction() и тд). На основе этих знаний, применить транзакции правильно.

**Comment by kjluh** [comment]
Я знаю что JPA использует транзакции, у меня в проекте всего 2 репозитория которые JPA. В сервисах которые с ними работают нет транзакций.
